title: Toktarov Notes
description: "Философия, политика и цифровая современность: заметки, подкаст, обзоры статей и полезные ссылки для учёных."
lang: ru
timezone: Asia/Almaty

url: "https://ermekuss.github.io"
baseurl: "/blog"

permalink: /posts/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM

excerpt_separator: "<!--more-->"

social:
  facebook: "https://www.facebook.com/ermekuss"
  x: "https://x.com/ermekuss"
  linkedin: "https://www.linkedin.com/in/yermek-toktarov-b7996b58/"

plugins:
  - jekyll-feed
